"""add rejection_reason

Revision ID: 405129dccea6
Revises: 8e34d2ba6ecc
Create Date: 2026-07-09 14:15:57.042110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '405129dccea6'
down_revision: Union[str, None] = '8e34d2ba6ecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('rejection_reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loans', 'rejection_reason')
    # ### end Alembic commands ###
