"""add_category_location_fines

Revision ID: 61264ef1b94a
Revises: 001_initial
Create Date: 2026-07-07 20:22:17.128484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '61264ef1b94a'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('items', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('loans', sa.Column('actual_return_time', sa.DateTime(), nullable=True))
    op.add_column('loans', sa.Column('fine_amount', sa.Integer(), nullable=False))
    op.add_column('loans', sa.Column('is_fine_paid', sa.Boolean(), nullable=False))
    op.add_column('rooms', sa.Column('location', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))
    op.add_column('rooms', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'image_url')
    op.drop_column('rooms', 'location')
    op.drop_column('loans', 'is_fine_paid')
    op.drop_column('loans', 'fine_amount')
    op.drop_column('loans', 'actual_return_time')
    op.drop_column('items', 'image_url')
    op.drop_column('items', 'category')
    # ### end Alembic commands ###
